languageCode = "en"
languageName = "English"
title = "Baldwyns Park Scouts & Guides, Joydens Wood"
weight = 1

[params]
copyright = "Â© { year }, 1st Baldwyns Park Scout and Guide Group, charity no: 303501 "
dateFormat = "2 January 2025"
# logo = "img/logo.png"
description = "Baldwyns Park Scouts & Guides, Joydens Wood"
displayName = "EN"
isoCode = "en"
rtl = false

[params.author]
# image = "img/avatar.png"
headline = "The Home of Scouting & Guiding in Joydens Wood"
name = "Baldwyns Park Scouts & Guides, Joydens Wood"

# bio = "A little bit about you"
# links = [
# { link = "https://baldwynsparkscoutsandguides.org/" },
# { github = "https://github.com/Baldwyns-Park-Scouts-and-Guides/website" },
# { location = "https://twitter.com/burufugu" }
# ]
