# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Site Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["*"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Get URL
  deploy-settings:
    runs-on: ubuntu-latest
    steps:
      - name: Get Pages URL
        id: get-gh-url
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh_url=$(gh api "repos/$GITHUB_REPOSITORY/pages" --jq '.html_url')
          echo Pages url: ${gh_url}
          echo "gh_url=${gh_url}" >> "$GITHUB_OUTPUT"
    outputs:
      gh_url: ${{ steps.get-gh-url.outputs.gh_url }}

  # Build job
  build:
    runs-on: ubuntu-latest
    needs: deploy-settings
    steps:
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 0.152.2
          extended: true

      - name: Check out code into the Go module directory
        uses: actions/checkout@v5
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
          GH_URL: ${{needs.deploy-settings.outputs.gh_url}}
        run: |
          hugo -d ./public --baseURL ${{ env.GH_URL }}

      - name: Upload artifact
        if: github.ref   == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public

  # Deployment job
  deploy:
    if: github.ref   == 'refs/heads/main'
    needs: build
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
